name: CI Pipeline

on:
  push:
    branches: [ "main", "feature/*" ] # При любом пуше в main или ветки feature
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # GitHub выделит нам сервер на Linux Ubuntu

    steps:
    - name:  Скачиваем код из репозитория
      uses: actions/checkout@v4

    - name:  Устанавливаем Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm' # Ускоряет установку зависимостей

    - name:  Устанавливаем зависимости
      run: npm install

    - name: 🧪 Запускаем Vitest
      run: npm test
